name: encrypting_rpc
services:
  rpc:
    image: shutter-network/encrypting-rpc
    restart: always
    build:
      context: ../
    env_file: .env
    ports:
      - "8546:8546"
      - 4000:4000
    command: >
      start
      --signing-key ${SIGNING_KEY}
      --key-broadcast-contract-address ${KEY_BROADCAST_CONTRACT_ADDRESS}
      --sequencer-address ${SEQUENCER_CONTRACT_ADDRESS}
      --keyper-set-manager-address ${KEYPER_SET_MANAGER_CONTRACT_ADDRESS}
      --rpc-url ${UPSTREAM_RPC}
      --delay-in-seconds ${DELAY_IN_SECONDS}
      --metrics-port ${METRICS_PORT}
      --metrics-enabled ${METRICS_ENABLED}
      --metrics-host ${METRICS_HOST}
      --fetch-balance-delay ${FETCH_BALANCE_DELAY}
      --dbUrl ${DB_URL}
      --wait-mined-interval ${WAIT_MINED_INTERVAL}
    depends_on:
      - postgres
    labels:
      caddy: "${SERVICE_DOMAIN_NAME}"
      caddy.@browser: "method GET"
      caddy.redir: "@browser https://blog.shutter.network/shutterized-gnosis-chain-is-now-live/"
      caddy.reverse_proxy: "{{ upstreams 8546 }}"
      caddy.header.Access-Control-Allow-Origin: "*"
      caddy.header.Access-Control-Allow-Methods: "GET, POST, OPTIONS"
      caddy.header.Access-Control-Allow-Headers: "Content-Type, Authorization"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    restart: always
    volumes:
      - ${DATA_DIR:-./data}/caddy:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    labels:
      caddy.email: "devops@brainbot.com"

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db-data:/var/lib/postgresql/data

  setup-postgres:
    image: postgres:14-alpine
    entrypoint: ["psql", "-f", "/migration.sql"]
    environment:
      PGHOST: "postgres"
      PGDATABASE: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
    volumes:
      - ./migration.sql:/migration.sql:ro
    depends_on:
      postgres:
        condition: service_healthy

  node_exporter:
    image: prom/node-exporter:latest
    container_name: my_node_exporter
    ports:
      - "9100:9100"
